image: ubuntu:latest

before_script:
  - apt-get update
  - apt-get install openssh-client git-core -y
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
  - ssh-keyscan openvet.tk >> ~/.ssh/known_hosts

stages:
 #  - build
  - deploy

deploy_dev:
  stage: deploy
  script:
    - echo "Deploying to dev.openvet.tk"
  environment:
    name: OpenVet dev
    url: https://dev.openvet.tk
  only:
    - dev

deploy:
  stage: deploy
  script:
    - echo "Deploying to www.openvet.tk"
    - scp -r /builds/Khrid/HES_644-1_OpenData_OpenVet/html/* david@openvet.tk:/var/www/openvet.tk/html
  environment:
    name: OpenVet production
    url: https://www.openvet.tk
  only:
    - master 
