image: alpine

before_script:
  - apk add --update openssh-client bash git
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
  - ssh-keyscan $SSH_REMOTE_HOST >> ~/.ssh/known_hosts

stages:
 #  - build
  - deploy
  - api

deploy_dev:
  stage: deploy
  script:
    - echo "Deploying to dev.openvet.tk"
    - scp -r $CI_PROJECT_DIR/html/* $SSH_REMOTE_USER@$SSH_REMOTE_HOST:$SSH_REMOTE_DIR_DEV
  environment:
    name: OpenVet dev
    url: https://dev.openvet.tk
  only:
    - dev

deploy:
  stage: deploy
  script:
    - echo "Deploying to www.openvet.tk"
    - scp -r $CI_PROJECT_DIR/html/* $SSH_REMOTE_USER@$SSH_REMOTE_HOST:$SSH_REMOTE_DIR_PROD
  environment:
    name: OpenVet production
    url: https://www.openvet.tk
  only:
    - master 

api:
  stage: api
  script:
    - echo "Deploying API keys"
    - echo $API_KEY_TELSEARCH > $CI_PROJECT_DIR/.api_key_telsearch
    - scp $CI_PROJECT_DIR/.api_key_telsearch $SSH_REMOTE_USER@$SSH_REMOTE_HOST:$API_KEY_LOCATION
